language:
- c
- cpp

# clang is not supported for poppler
compiler: gcc

cache:
- ccache

os: linux
dist: xenial

sudo: required

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "DxwzqXcJV/9qPwUCi7DQrqzeU73ACRhS0i8suV9tYpUDJ7ZuwwSK/GMVt2jMTNjZbJwKFv8ELLu0MIdTfX3UvG+++lfxLx4yldEwl4CtjPJaClB2rTou2SAiZPMBMyX6eHKfx0XB4xtsqwtKRIvF47tB9i3w+aPcb8C4DE6hXmU="


addons:
  coverity_scan:
    project:
      name: "peetCreative/xournalpp"
      description: "Notetaking software designed around a tablet."
    notification_email: peter_klausing@wh2.tu-dresden.de
    build_command_prepend: "cmake .. -DBUILD_POPPLER=ON -DENABLE_MATHTEX=ON -DENABLE_CPPUNIT=ON -DUNSTABLE_LAYERS_SIDEBAR=ON"
    build_command: "make LIBOPENJPEG2_LIBRARIES=-ljpeg LIBOPENJPEG2_INCLUDE_DIR="
    branch_pattern: coverity_scan

# get pagkages with apt-get manually because the apt addon isn't supported on Travis' Xenial
before_script:
  - "sudo apt-get update"
  - "sudo apt-get install cmake libboost-all-dev libcppunit-dev dvipng texlive libopenjp2-7-dev libglade2-dev"
  - "mkdir build"
  - "cd build"

script:
  - "cmake .. -DCMAKE_DEBUG_INCLUDES_LDFLAGS=ON -DBUILD_POPPLER=ON -DENABLE_MATHTEX=ON -DENABLE_CPPUNIT=ON -DUNSTABLE_LAYERS_SIDEBAR=ON -DDEBUG_COMPILE=ON"
  - "make LIBOPENJPEG2_LIBRARIES=-ljpeg LIBOPENJPEG2_INCLUDE_DIR="
  - "ctest"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4879506130dac18d2f63
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

